# Generated by Django 5.2 on 2026-05-24 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogindexpage_blogcategorypage_blogdetailpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category', verbose_name='category'),
        ),
    ]
