# Generated by Django 5.2 on 2026-05-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogdetailpage_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetailpage',
            name='create_ua_draft',
            field=models.BooleanField(default=False, help_text='Create a Ukrainian draft copy after saving this Russian article. The Ukrainian category page must already exist.', verbose_name='create Ukrainian draft'),
        ),
    ]
